---
- name: Setup tftp to backup NXOS running-config
  hosts: localhost
  gather_facts: no

  tasks:
    - name: install  xinetd & tftp-server
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "xinetd"
        - "tftp-server"

    - name: make tftp_shared_directory
      file:
        path: /home/vagrant/tftp_shared
        state: directory
        mode: 0777

    - name: modify tftp's config (1)
      become: yes
      replace:
        path: /etc/xinetd.d/tftp
        regexp: 'root'
        replace: 'vagrant'

    - name: modify tftp's config (2)
      become: yes
      replace:
        path: /etc/xinetd.d/tftp
        regexp: '-s /var/lib/tftpboot'
        replace: '-c -p -u vagrant -s /home/vagrant/tftp_shared'

    - name: modify tftp's config (3)
      become: yes
      lineinfile:
        path: /etc/xinetd.d/tftp
        regexp: 'disable'
        line: 'disable = disable'

    - name: modify tftp service's config
      become: yes
      replace:
        path: /usr/lib/systemd/system/tftp.service
        regexp: '-s /var/lib/tftpboot'
        replace: '-c -p -u vagrant -s /home/vagrant/tftp_shared'

    - name: selinux change to permissive on ansible-server
      become: yes
      selinux: policy=targeted state=permissive

    - name: service daemon restart
      become: yes
      systemd:
        state: restarted
        daemon_reload: yes
        name: tftp

    - name: service restart
      become: yes
      service:
        name: xinetd
        state: restarted


- name: Request to backup NXOS's running-config
  hosts: NXOS
  gather_facts: no
  connection: local

  tasks:
    - name: running-config backup
      nxos_command:
        commands: 'copy running-config tftp://192.168.1.10/n9k-running-confg vrf management'
        transport: cli


- name: selinux restore on ansible-server
  hosts: localhost
  gather_facts: no
  tasks:
    - name: selinux change to enforcing
      become: yes
      selinux: policy=targeted state=enforcing