---
- name: Setup for chrony-server
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - name: Add allow address ragne
      lineinfile:
        path: /etc/chrony.conf
        line: 'allow 192.168.1.0/24'
        insertafter: '# Allow NTP client'

    - name: Local as stratum 3
      lineinfile:
        path: /etc/chrony.conf
        line: 'local stratum 3'
        insertafter: '# Serve time even'

    - name: Chrony restart to apply the policy
      service:
        name: chronyd
        state: restarted