---
- name: Setup linux timezone
  hosts: CentOS:Ubuntu
  gather_facts: no
  become: yes

  tasks:
    - name: set timezone to Asia/Seoul
      timezone: name=Asia/Seoul

- name: Setup windows timezone
  hosts: Win
  gather_facts: no

  tasks:
    - name: set timezone to 'Korea Standard Time'
      win_timezone: timezone='Korea Standard Time'

- name: Setup NXOS timezone with ntp configuration
  hosts: NXOS
  gather_facts: no
  connection: local

  tasks:
    - name: ntp configuration
      nxos_config:
        lines: 'ntp server 192.168.1.10 use-vrf management'
        save: yes
        transport: cli
    - name: timezone to UTC 9 0
      nxos_config:
        lines: 'clock  timezone UTC 9 0'
        save: yes
        transport: cli