---
- name: Add NXOS and ssh_key
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Add "/etc/ansible/hosts"
      become: yes
      lineinfile:
        path: /etc/ansible/hosts
        line: "{{ item }}"
      with_items:
        - "[NXOS]"
        - "192.168.1.201 ansible_ssh_user=admin"

    - name: sshkey gen
      shell: ssh-keyscan 192.168.1.201 >> ~/.ssh/known_hosts

- name: nxos_ping
  hosts: NXOS
  gather_facts: no
  connection: local

  tasks:
    - name: ping test from nxos to ansible-server
      nxos_ping:
        dest: 192.168.1.10
        vrf: management